config/routes.rb
Memo::Application.routes.draw do
  
  devise_for :user
  root to: 'pages#home'
  resources :tasks, except: [:index]

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :manage, Task, user_id: user.id
    
    
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/tarefas.rb
class Tarefas < ActiveRecord::Base
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :title
  validates_presence_of :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  has_many :tasks

end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :authenticate_user!
  respond_to :html, :json
  layout :layout_by_controller

  protected

  def layout_by_controller
    devise_controller? ? 'devise' : 'application'
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @tasks = Task.accessible_by(current_ability)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/tarefas_controller.rb
class TasksController < ApplicationController
  def new
    @task = Task.new
  end
  def create
    @task = Task.create(task_params)
    @task = Task.all
  end
  def delete
    @task = Task.find(params[:id])
    @task.destroy
    @task = Task.all
  end
  def show
    @task = Task.all
  end
  private
  def task_params
    params.require(:task).permit(:title, :note, :completed)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def new
    @task =Task.new
    render :show_form
  end
  
  def create
    @task = Task.new(task_params)
    @task.user = current_user
    authorize! :create, @task
    save_task
  end

  def destroy
    @task = Task.find(params[:id])
    authorize! :destroy, @task
    @task.destroy
    @tasks = Task.accessible_by(current_ability)
  end

  def edit
    @task = Task.find(params[:id])
    authorize! :edit, @task
    render :show_form
  end

  def update
    @task = Task.find(params[:id])
    @task.update_attributes(task_params)
    authorize! :update, @task
    save_task
  end

  private
  def save_task
    if @task.save
      @tasks = Task.all
      render :hide_form
    else
      render :show_form
    end
 end
  def task_params
    params.require(:task).permit(:title, :note, :completed, :urge)
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
   def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tarefas_helper.rb
module TarefasHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Projeto Final OO
    = stylesheet_link_tag   "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    .row-fluid
      .span10.offset1
        .hero-unit.text-center
          %h1
            %a{:href => "http://localhost:3000/"} To-Dos
            %small O que eu ia fazer?
          .text-center
            %strong= current_user.email
          = link_to 'New task', new_task_path, class: 'btn btn-primary btn-lg btn-block', remote: true
          = link_to "Sign in with Facebook", new_user_session_path, class: 'btn btn-primary btn-lg btn-block'
          = link_to 'Login', new_user_session_path, class: 'btn btn-default btn-lg btn-block'
          = link_to "Logout", destroy_user_session_path, method: :delete, :class => 'btn btn-default btn-lg btn-block'
    .container
      .jumbotron
        %img{:alt => "Smiley face", :height => "30",:vspace => "10", :src => "http://premioengenho.com.br/wp-content/uploads/2011/08/UnB-premio-engenho.jpg", :width => "600"}/
        =yield 

app/views/layouts/devise.html.haml
!!!
%html
  %head
    %title Todo
    = stylesheet_link_tag "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    .row-fluid
      .span10.offset1
        .hero-unit.text-center
          %h1
            To-Dos
          %p 
            Apenas usúarios cadastrados
    .row-fluid
      .span4.offset4
        = yield

app/views/pages/home.html.haml
#task-list.container
  = render partial: 'tasks/task_list', locals: {tasks: @tasks}
#modal.modal.fade

app/views/tasks/_tarefa_form.html.haml
.modal-header
  %h1 Nova Tarefa!
= simple_form_for task, class: 'clearfix' do |f|
  .modal-body
    = f.input :titulo
    = f.input :nota
    = f.input :dia
  .modal-footer
    = f.submit 'Adicionar', class: 'btn btn-primary'    

app/views/tasks/_task_form.html.haml
.modal-header
  %h1 New Task
= simple_form_for task, class: 'clearfix', remote: true do |f|
  .modal-body
    = f.input :title
    = f.input :note
    = f.input :completed
    = f.input :urge
  .modal-footer
    = f.submit 'Adicionar', class: 'btn btn-primary'

app/views/tasks/_task_list.html.haml
.container
  - if @tasks.empty?
    %span.text-error Não há tarefas!
  - else
    %table.table.table-hover.table-bordered
      %thead
        %tr
          %th X
          %th Titulo
          %th Criada em
          %th Término em
          %th Urgente? 
          %th Notas 
      %tbody
        - @tasks.each do |task|
          - if task.urge == true
            %tr.error
              %td.erro
                = link_to task_path(task), remote: true, method: :delete, data: {confirm: "Apagar a tarefa #{task.title}?"} do
                  %i.icon-remove
              %td
                %strong= task.title
              %td.text-info= task.created_at
              %td.text-success= task.completed
              %td.text-error= task.urge
              %td.text-error= task.note
          - else
            %tr
              %td
                = link_to task_path(task), remote: true, method: :delete do 
                  %i.icon-remove
              %td         
                %strong.text-info= task.title
              %td.text-info= task.created_at 
              %td.text-success= task.completed
              %td.text-info= task.urge
              %td.text-success= task.note

app/views/tasks/_usuario_form.html.haml
.modal-header
  %h1 Novo Usuario!
= simple_form_for usuario, class: 'clearfix', remote: true do |f|
  .modal-body
    = f.input :email
    = f.input :password
    = f.input :password_confirmation
  .modal-footer
    = f.submit 'Cadastrar', class: 'btn btn-primary'

app/views/tasks/create.js.erb
$('#task-list').html('<%= j(render partial: 'tasks/task_list', locals: {tasks: @tasks}) %>');
$('#modal').modal('hide');

app/views/tasks/destroy.js.erb
$('#task-list').html('<%= j(render partial: 'task_list', locals: {tasks: @tasks})%>');

app/views/tasks/hide_form.js.erb
$('#task-list').html('<%= j(render partial: 'tasks/task_list', locals: {tasks: @tasks}) %>');
$('#modal').modal('hide');

app/views/tasks/new.js.erb
m = $('#modal');
m.html('<%= j(render partial: 'task_form', locals: {task: @task}) %>'); 
m.modal('show');

app/views/tasks/newuser.js.erb
m = $('#modal');
m.html('<%= j(render partial: 'tasks/usuario_form', locals: {usuario:@usuario) %>');
m.modal('show');

app/views/tasks/show_form.js.erb
m = $('#modal');
m.html('<%= j(render partial: 'task_form', locals: {task: @task}) %>'); 
m.modal('show');